### ISSUE TITLE
export logs

### ISSUE THREAD

**Issue by lucamp** [ibbaa/keepitup#2]
Hi, it would be nice to have the ability to export logs.

Every task should be saved with "taskIP_startdate_starttime.txt" so logs will be easy to recognise

Thanks
Luca

**Comment by ibbaa** [comment]
It's already possible to export logs. "Export configuration" includes the logs for all network tasks. It's not really readable by default since it's JSON and includes everything else but with additional tools that format JSON it's feasible. I don't think it's worth the effort to provide an additonal exporter. The current logs are limited to 100 entries per task anyway and I'm not sure how useful it will be to export this on demand. The 100 entries are a bit arbitrary and could possibly be increased but the main problem is the limited size of the internal storage per app. External storage is also limited but the limit is much larger. I'm thinking about providing file logging additionally to the current database logging. Not "on demand" as an export, every log entry that is written to the database will also be written to a file (if enabled). I'm not sure about log rotation but with the large amount of memory and the small size of log files there will be plenty of space and it will be possible to store much much more than 100 entries, since the user is able to delete/archive log files manually (which is not possible with the internal database, there must be some kind of memory management resp. log rotation, currently it deletes the oldest log if there are more than 100 entries).

**Comment by ibbaa** [comment]
The new version 1.1.0 provides file logging as described.
