### ISSUE TITLE
Feature request: notify when status changes 

### ISSUE THREAD

**Issue by Pharell** [ibbaa/keepitup#4]
I recently found your nice app and tried to use it to track when devices come up in my network as well as when they are down. 

Currently the settings allow that a notification is triggered only when a device is down but not when it is up again. 

Maybe this can be added without too much effort, so that every change of availability status (up/down, down/up) raises a notification. Or if easier just a negation of the current mode so that a notification is only shown when a device is available. 

And as deluxe version of this feature, maybe also only log these events and not every try.

**Comment by ibbaa** [comment]
Thanks for your suggestion. This can certainly be done. At the moment I don't have too much time to spend on this project and all the effort goes into raising the target version and supporting the restrictions of newer Android versions, since Google is planning to block "outdated" apps even for sideloaded apps (i.e. those which are not in the official play store). So I'm not implementing any new features for a while but I'm accepting merge requests. I leave this open until someone implements it or unitl I find the time to do it.

**Comment by ibbaa** [comment]
The new version 1.2.0 contains a setting that a notification is triggered on status change up -> down and down -> up. The default is still notification on failure but it can be switched in the settings.

**Comment by Pharell** [comment]
Thank you very much for your time! I installed the new version immediately and I am happy, to get a notification about my network devices coming up (and down). Keep it up! :-D
