### ISSUE TITLE
[Feature request] Run ping only till the first success

### ISSUE THREAD

**Issue by baack** [ibbaa/keepitup#5]
[Feature request] Run ping only till the first success

Currently user can choose the number of pings to make. But in fact quite often 1 successful in enough to understand that the server is online. While 1 fail should not be enough because the problem can be with user's mobile connection, so additional attempts would be required.

Proposal: Add a new checkbox "Stop after the first successful" near the ping amount (3 by default) settings.

**Comment by ibbaa** [comment]
Thanks for the suggestion. I see the point but this cannot be done in the way it's currently implemented. Java/Android API does not provide a library for ICMP/ping. The app simply calls the system ping and parses the output for additional info, Success is decided by the the ping process return code (0=success). The ping count is the option "-c" for the ping command and it simply pings n times and does not stop prematurely. Of course I could do several pings with "-c 1" and aggregate everything by myself but I think it's to much effort for to little gain. The current behaviour also makes sense and I like it, so it would mean 2 different implementations and a switch.

**Comment by baack** [comment]
> Of course I could do several pings with "-c 1" and aggregate everything by myself but I think it's to much effort for to little gain.

In this case I would definitely do that, call it several times.
The current behavior is not making much sense to me. E.g. what should happend if user set 3 pings and got 2 success and 1 fail? Should the user be notified that server is down or up? To my opinion - it is up, but that means that all pings out of 3 were useless except the first that succeeded, which is exactly what I proposed.

Maybe I am missing some use case for the current behavior.

**Comment by ibbaa** [comment]
It's the "standard" behaviour of the ping utility. It reports overall success on at least one successful attempt. For me this makes the most sense. More pings on one try offer additional info, like average latency. However with the suggested way I can do whatever behaviour seems reasonable and I'm not fixed to ping behavior, so it's obviously better but a matter if it's worth the effort, since now it may do additonal pings that may not be necessary, depending on ones view on this, but do not hurt too much either. I'll think about it when I find the time for the pings. The time schedule feature will take a lot of time anyway. Maybe I'm in the mood to do other things between, but not now.

**Comment by ibbaa** [comment]
Release 1.5.0 does provide "stop on success" switch for ping and connect
